### ISSUE TITLE
install_linux_deb script changes emacs

### ISSUE THREAD

**Issue by williamdemeo** [TypeFunc/uh-mfc#3]
Can we find a better alternative to significantly messing with one's emacs settings?

It's probably not an issue for those who don't have any serious emacs customizations, but I'm not really comfortable with a substantially altered emacs environment.  

Also, the emacs settings configured by the install script do not work on my machine (though perhaps that's because my install didn't finish).

Here's an error message I get when launching emacs after my (aborted) run of the install_linux_deb script:

    Warning (initialization): An error occurred while loading `/home/wjd/.emacs':
    
    File error: Cannot open load file, no such file or directory, tidal
    
    To ensure normal operation, you should investigate and remove the
    cause of the error in your initialization file.  Start Emacs with
    the `--debug-init' option to view a complete error backtrace.

**Comment by jfennick** [comment]
Hi,
FYI the script executes these four lines:

echo "moving ~/.emacs to ~/.emacsbackup"
mv ~/.emacs ~/.emacsbackup
echo "copying dotemacs to ~/.emacs"                                                     
cp dotemacs ~/.emacs

I wasn't comfortable simply appending my .emacs file to the user's, so I just renamed the user's .emacs file.  You probably didn't see this echo output among all of the other output.  For now you can just copy and paste the contents of my .emacs file into yours.

**Comment by williamdemeo** [comment]
Yes, I figured something like that was happening, so I wasn't too worried about not being able to recover my old emacs settings.

I think it's better to tell the user what to append to their .emacs file, like you did in the comment above, rather than moving the existing .emacs file aside and replacing it with a new one.

Also, I now see why the new .emacs file didn't work for me.  It assumes haskelltalk is installed in `~/uh-mfc/haskelltalk`, whereas mine is actually in `~/git/TEAMS/TypeFunc/gh/uh-mfc/haskelltalk`.  Of course, there's no way you could have known that, which is another reason it's probably better to just tell the user to add some lines to their emacs file---it will hopefully make them realize that they may need to adjust the path to `haskelltalk`.

**Comment by williamdemeo** [comment]
I'm going to accept my pull request so I can close this issue.

**Comment by jfennick** [comment]
William,
You need to give me more than 12 hours to examine your issues.  I'm going to discuss this in the next talk, but the number one reason these install scripts exist is to install system packages.  I threw in editor configurations for people who wanted a one-click automated install, while NOT deleting your .emacs file etc for advanced users.  Frankly, I'm not on board with line 3 of the updated script which claims joint ownership / authorship of the file.  Getting the system packages installed and working is really not in the same league as fixing path / editor configuations.  (For an outline, see the new dependency_management file.)  I don't think anyone needs to claim ownership, but if you want to split off path / editor configuration into a separate script then go for it.

More importantly, this issue is not quite resolved.  For various reasons, there is at least one more hard coded path in the ghciscript file.  There is also the issue that install_linux_rpm has not been updated yet either.  Unfortunately I have some deadlines Friday, so if you don't want to wait until the weekend then feel free to make whatever changes you feel appropriate.

**Comment by williamdemeo** [comment]
I am more than happy to delete my name from the script.  I only put it there, along with my email address, so that people would know who to complain to---or ask for help from---if they had trouble with the script. Putting my name there was an offer to help users (and you!) get this working properly.  It is not a claim of "ownership".

I will remove name from the file now.  On second thought, please reset the HEAD of the repo back to your old script.  I'd rather not be involved in developing this script going forward.

As for accepting the pull request too quickly, I thought an earlier message of yours said it was fine to commit these changes.  Sorry if I misinterpreted.  Anyway, II have no problem with undoing the merge and reverting back to your version of the script.  In fact, let's do that.

Also, let's keep in mind, this is just an install script.

**Comment by williamdemeo** [comment]
The install script was reverted to the previous version by Jake.  I'll leave this issue open in case Jake wants to address it.

**Comment by jfennick** [comment]
Sorry for the delay, but I just committed a change which hopefully addresses your issues.  My goal was to have a fully automated install script, but due to the emacs config and path issues, I've decided to simply print a message telling the user to modify their .emacs file and/or paths.  Similarly, installing nvidia cuda can be a whole can of worms, so I've left those lines of the install script to the user to uncomment as well.  So unless you feel there is still an issue, I'm going to mark this as closed.
